version: '3'
services:
  db: 
    image: eqalpha/keydb
    command: keydb-server /etc/keydb/keydb.conf --requirepass dalong  --masterauth dalong --active-replica yes --replicaof db2  6379
    ports:
     - 6379:6379
  db2: 
    image: eqalpha/keydb
    command: keydb-server /etc/keydb/keydb.conf   --requirepass dalong  --masterauth dalong --active-replica yes --replicaof db  6379
    ports:
     - 6380:6379
  haproxy: 
    image: haproxytech/haproxy-debian:2.7.5
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    ports:
    - "5001:5000"
  nchan:
     image: openresty/openresty:1.21.4.1-6-alpine-fat
     privileged: true
     cap_add:
       - ALL
     ports:
     - "80:80"
     volumes:
     - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
     - "./app.log:/opt/app.log"